### PR TITLE
Mock morpheus server - returns empty response

### PR DESCRIPTION
**Pull request by AdamBalski**
mock server, empty response, no API for sending feedback yet

### CODE REVIEW

**Comment by kapiw04** [comment]
LGTM, are you planning on adding some comments?

**Comment by AdamBalski** [comment]
> LGTM, are you planning on adding some comments?

hey, I am not sure. I added a bit more extensive README.md, but not a lot of comments as far as code goes, can you point me to a place you find unclear?

**Comment by kapiw04** [comment]
Great, now everything seems clear.

**Review by kapiw04 — APPROVED** [review]
LGTM

**Pull request merged**
